version: '3.8'
services:

    react-app:
        build: 
            context: ./react/app
            dockerfile: Dockerfile   # Correct path to the Dockerfile for the React app
        container_name: react-app
        ports: 
            - "3000:3000"
        depends_on:
            - spring-boot-app   # Ensure that the Spring Boot app starts first

    spring-boot-app:
        build: 
            context: ./spring-boot
            dockerfile: Dockerfile  # Path to the Dockerfile for the Spring Boot app
        container_name: spring-boot-app
        ports:
            - "8080:8080"
        depends_on:
            - postgres   # Ensure that PostgreSQL starts first
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/shopDB
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password

    postgres:
        image: postgres
        container_name: sp-postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: shopDB
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data:
