server:
port: 8080

spring:

    logging:
        level:
            org.hibernate.SQL: WARN

    datasource:
        url: jdbc:postgresql://localhost:5432/shopDB
        username: user
        password: password

    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show_sql: false
    main:
        web-application-type: servlet

    mail:
        host: smtp.gmail.com
        port: 587
        username: dobrev.testmail@gmail.com
        password: gxmboitkckkloeeh

        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
